# Generated by Django 2.0.7 on 2018-07-14 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('dealerID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=12)),
                ('isBlocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Dealers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.IntegerField()),
                ('colour', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('homoligation', models.BooleanField(default=False)),
                ('custom_clearance', models.BooleanField(default=False)),
                ('scheduled_completion_date', models.CharField(max_length=100)),
                ('deposit_received', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('dealerID', models.ForeignKey(db_column='dealerID', on_delete=django.db.models.deletion.CASCADE, to='appgu.Dealers')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
