# Generated by Django 2.0 on 2018-10-12 21:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(max_length=12)),
                ('isBlocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Dealers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('link', models.URLField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Events_Tuscany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('link', models.URLField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MapDealers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('address', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, default='default_banner.png', null=True, upload_to='news/banners/')),
                ('title', models.CharField(max_length=1000)),
                ('headline', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('quote', models.CharField(max_length=1000)),
                ('quotefooter', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPosts_Tuscany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, default='default_banner.png', null=True, upload_to='news/banners/')),
                ('title', models.CharField(max_length=1000)),
                ('headline', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('quote', models.CharField(max_length=1000)),
                ('quotefooter', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=1000)),
                ('colour', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('homologation', models.BooleanField(default=False)),
                ('custom_clearance', models.BooleanField(default=False)),
                ('additional_comments', models.CharField(max_length=1000)),
                ('scheduled_completion_date', models.CharField(max_length=100)),
                ('deposit_received', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='portal_invoices/')),
                ('dealerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_order', to='appgu.Dealers')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=1000)),
                ('headline', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, default='default_vehicle.png', null=True, upload_to='vehicles/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles_Tuscany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=1000)),
                ('headline', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, default='default_vehicle.png', null=True, upload_to='vehicles/')),
            ],
        ),
    ]
