# Generated by Django 2.0.6 on 2018-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='model',
            field=models.CharField(max_length=1000),
        ),
    ]
