# Generated by Django 2.0.7 on 2018-07-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='homoligation',
            new_name='homologation',
        ),
    ]
