# Generated by Django 2.0.6 on 2018-07-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0002_auto_20180709_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='username',
            field=models.CharField(default='lel', max_length=100),
            preserve_default=False,
        ),
    ]
