# Generated by Django 2.0 on 2018-10-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0002_auto_20181012_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdealers',
            name='link',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
