# Generated by Django 2.0.6 on 2018-07-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0002_auto_20180719_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='additional_comments',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
