# Generated by Django 2.0.7 on 2018-07-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0003_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, default='bow.png', null=True, upload_to='static/shelby_vehicles/'),
        ),
    ]
