# Generated by Django 2.0 on 2018-10-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0003_mapdealers_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mapdealers',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
