# Generated by Django 2.0.6 on 2018-07-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0003_orders_additional_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='invoice',
            field=models.FileField(blank=True, default='default_invoice.pdf', null=True, upload_to='invoices/'),
        ),
    ]
