# Generated by Django 2.0.7 on 2018-07-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0004_auto_20180714_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, default='bow.png', null=True, upload_to=''),
        ),
    ]
