# Generated by Django 2.0 on 2018-10-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0004_auto_20181013_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='extra',
            field=models.CharField(default='', max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicles_tuscany',
            name='extra',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
