# Generated by Django 2.0.6 on 2018-07-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0005_auto_20180721_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, default='bow.png', null=True, upload_to='vehicles/')),
                ('title', models.CharField(max_length=1000)),
                ('headline', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('quote', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('writtenby', models.ForeignKey(db_column='dealerID', on_delete=django.db.models.deletion.CASCADE, to='appgu.Dealers')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
