# Generated by Django 2.0 on 2018-11-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0005_auto_20181014_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='extra',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles_tuscany',
            name='extra',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
