# Generated by Django 2.0.6 on 2018-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0006_auto_20180722_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='banner',
            field=models.ImageField(blank=True, default='default_banner.png', null=True, upload_to='news/banners/'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, default='default_vehicle.png', null=True, upload_to='vehicles/'),
        ),
    ]
