# Generated by Django 2.0.6 on 2018-07-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0008_newsposts_quotefooter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='portal_invoices/'),
        ),
    ]
