# Generated by Django 2.0.7 on 2018-08-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0011_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(default='2018-08-01'),
            preserve_default=False,
        ),
    ]
