# Generated by Django 2.0.7 on 2018-08-01 23:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0012_events_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDealers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
