# Generated by Django 2.0.7 on 2018-08-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0013_mapdealers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdealers',
            name='latitude',
            field=models.FloatField(default=43.43443),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapdealers',
            name='longitude',
            field=models.FloatField(default=43.344332),
            preserve_default=False,
        ),
    ]
