# Generated by Django 2.0.7 on 2018-08-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0014_auto_20180802_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdealers',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
