# Generated by Django 2.0.7 on 2018-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0015_auto_20180802_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
