# Generated by Django 2.0.7 on 2018-08-18 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appgu', '0016_auto_20180804_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_Tuscany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('link', models.URLField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsPosts_Tuscany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, default='default_banner.png', null=True, upload_to='news/banners/')),
                ('title', models.CharField(max_length=1000)),
                ('headline', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('quote', models.CharField(max_length=1000)),
                ('quotefooter', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('writtenby', models.ForeignKey(db_column='dealerID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles_Tuscany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=1000)),
                ('headline', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, default='default_vehicle.png', null=True, upload_to='vehicles/')),
            ],
        ),
    ]
