# Generated by Django 2.0 on 2018-08-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0018_auto_20180820_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='description_en',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='description_nl',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
