# Generated by Django 2.0 on 2018-08-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0019_auto_20180820_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='headline_en',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='headline_nl',
        ),
    ]
