# Generated by Django 2.0 on 2018-09-08 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0021_auto_20180908_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='writtenby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsposts_tuscany',
            name='writtenby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dealerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgu.Dealers'),
        ),
    ]
