# Generated by Django 2.0 on 2018-09-08 18:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0022_auto_20180908_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterModelManagers(
            name='dealers',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='dealerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_order', to='appgu.Dealers'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
