# Generated by Django 2.0 on 2018-10-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgu', '0023_auto_20180908_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdealers',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
